spring.application.name=canarias

# Puerto dinamico para Render
server.port=${PORT:8080}

# Configuracion PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-dark-fire-a2c3sd1l-pooler.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_E9baiISC4jAY
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desactivar Spring Security temporalmente para desarrollo frontend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
